version: '3.8'

name: bookeo
services:
  php:
    build: .
    container_name: php
    ports:
      - 8000:80
    volumes:
      - ./App:/var/www/html
    networks:
      - bookeo

  db:
    image: mysql:8.2.0-oraclelinux8
    container_name: mysqldb
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - dbBookeo:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: Bookeo
      MYSQL_USER: antoine
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    networks:
      - bookeo

  phpmyadmin:
    image: phpmyadmin:5.2.1-apache
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: password
    ports:
      - 8080:80
    depends_on:
      - db
    networks:
      - bookeo

volumes:
  dbBookeo:

networks:
  bookeo: